### ISSUE TITLE
UI: Main page

### ISSUE THREAD

**Issue by amclain** [ElixirSeattle/xebow#78]
We would like to redesign the main page of the Xebow Studio UI.

Notes
- The design is available [in Figma](https://www.figma.com/file/RMYWHeXJoDErWii1jm8C7k/Xebow?node-id=0%3A1) for margins, colors, fonts, etc.
- The following components were inspired by [tailwindcss](https://tailwindcss.com/), which can be included as a dependency. ([fomantic-ui](https://fomantic-ui.com/) is another option if we want more pre-built components.)
- Icons are from the [fontawesome](https://fontawesome.com/) free set.
- We need to try to load assets from the hardware rather than from the web, as the user may not have an internet connection when using the device. If this is not possible, reasonable alternatives should be used when the user is offline.
- The speedometer icon is intended to link to the telemetry dashboard at `/telemetry`. This should open in a new tab, as the page does not contain a way to navigate back to Xebow Studio.
- The hamburger icon is intended for menu items, like device settings, which might not exist in the first iteration. This is ok and the icon can be omitted.
- The design does not need to be pixel-perfect if another implementation looks better.

## Design

![Main](https://user-images.githubusercontent.com/4755047/87277785-dfad3e00-c497-11ea-9429-7e34f3a9e9d9.png)

**Comment by doughsay** [comment]
Suggested key CSS

```css
.key {
  position: absolute;
  height: 40px;
  background-color: mediumpurple;

  border-radius: 6px;
  box-shadow: inset 0 -1px 0 3px rgba(0, 0, 0, 0.1),
    0 0 0 1px rgba(0, 0, 0, 0.3);
  border-left: 1px solid rgba(0, 0, 0, 0.1);
  border-right: 1px solid rgba(0, 0, 0, 0.1);

  text-align: center;
  padding-top: 6px;
  font-size: 16px;
}
```
